describe('Register test', () => {
    it('register sida', () => {
      cy.visit('https://www.matchi.se/registration/user?returnUrl=%2Fprofile%2Fhome')
      cy.get('#facebookButton').eq(0).click()
      cy.wait(500)
      cy.get('input[name="email"]').eq(0).type('abc0010@gmail.com')
      cy.get('input[name="firstname"]').eq(0).type('CCC')
      cy.get('input[name="lastname"]').eq(0).type('WWW')
      cy.get('input[name="password"]').eq(0).type('1234567')
      cy.get('input[name="password2"]').eq(0).type('1234567')
       //cy.get('[style="width: 304px; height: 78px;"] > div > iframe"').eq(0).check() 
      cy.wait(1000)
      cy.get('#saveButton').eq(0).click()
    })
  })