apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metric:
        name: average-response-time-1m
      target:
        type: AverageValue
        averageValue: 1500
#
#---
#- type: Resource
#  resource:
#    name: memory
#    target:
#      type: Utilization
#      averageUtilization: 80
#- type: Resource
#  resource:
#    name: cpu
#    target:
#      type: Utilization
#      averageUtilization: 80
