apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-ehcache-config
data:
  ehcache.xml: |
    <ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="http://www.ehcache.org/ehcache.xsd">

        <cacheManagerPeerProviderFactory
                class="jgroups.JGroupsCacheManagerPeerProviderFactory"
                properties="file=jgroups/tcp.xml"/>

        <defaultCache
                maxElementsInMemory="10000"
                eternal="false"
                timeToIdleSeconds="300"
                timeToLiveSeconds="300"
                overflowToDisk="false"
                maxElementsOnDisk="10000"
                diskExpiryThreadIntervalSeconds="120"
                memoryStoreEvictionPolicy="LRU"
                statistics="true">


            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=false,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </defaultCache>

        <cache name="com.matchi.Sport"
                maxElementsInMemory="20"
                eternal="true"
                overflowToDisk="false"
                memoryStoreEvictionPolicy="LRU"
                statistics="true">
            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=false,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </cache>

        <cache name="com.matchi.Role"
                maxElementsInMemory="20"
                eternal="true"
                overflowToDisk="false"
                memoryStoreEvictionPolicy="LRU"
                statistics="true">
            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=false,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </cache>

        <cache name="com.matchi.FacilityProperty"
                maxElementsInMemory="15000"
                eternal="false"
                timeToIdleSeconds="900"
                timeToLiveSeconds="900"
                overflowToDisk="true"
                memoryStoreEvictionPolicy="LRU"
                statistics="true">
            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=false,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </cache>

        <!--  used to track timestamps of objects. recommended to never expire -->
        <cache
                name="org.hibernate.cache.UpdateTimestampsCache"
                maxElementsInMemory="5000"
                eternal="true"
                overflowToDisk="false"
                statistics="true">
            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=true,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </cache>

        <!--  used for query caches with no name set -->
        <cache
                name="org.hibernate.cache.StandardQueryCache"
                maxElementsInMemory="20000"
                maxElementsOnDisk="20000"
                eternal="false"
                timeToIdleSeconds="450"
                timeToLiveSeconds="900"
                overflowToDisk="false"
                statistics="true">
            <cacheEventListenerFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsCacheReplicatorFactory"
                    properties="replicateAsynchronously=true,
                            replicatePuts=true,
                            replicateUpdates=true,
                            replicateUpdatesViaCopy=false,
                            replicateRemovals=true"/>
            <bootstrapCacheLoaderFactory
                    class="net.sf.ehcache.distribution.jgroups.JGroupsBootstrapCacheLoaderFactory"/>
        </cache>

    </ehcache>
